# frozen_string_literal: true

require "shipengine/domains/addresses"
require "shipengine/domains/batches"
require "shipengine/domains/carriers"
require "shipengine/domains/carriers_accounts"
require "shipengine/domains/labels"
require "shipengine/domains/manifests"
require "shipengine/domains/package_pickups"
require "shipengine/domains/package_types"
require "shipengine/domains/rates"
require "shipengine/domains/service_points"
require "shipengine/domains/shipments"
require "shipengine/domains/shipsurance"
require "shipengine/domains/warehouses"
require "shipengine/domains/webhooks"
